### ISSUE TITLE
Barcode Image generation Failed.

### ISSUE THREAD

**Issue by zackhsuan** [yeahdongcn/RSBarcodes#11]
Hey

Thanks for your regular updates with this awesome lib. 
I have just encountered a bug. Say a barcode like this one: SLE00725088463420131227 will have a problem when generating barcode image from it. I believe the code type is code128. 

Could you please look into the issue?
I have actually credited your lib in my app :) Nearly finished but awaiting for a couple of introduction screens. I will update with me when my app got released. 

Cheers
Zac

**Comment by KevinJue** [comment]
'im actually have the same problem with EAN13 barcode "2011101286925"

how did you fix you problem ?

**Comment by zackhsuan** [comment]
@KevinJue Sorry can't really recall what happened back then. :(
