### ISSUE TITLE
Cannot scan barcode

### ISSUE THREAD

**Issue by haihw** [yeahdongcn/RSBarcodes#21]
Hi,
Thanks for your excellent library,
It works like a charm for most barcode I've tested except this one
Can you please help to check ?
![img_4590](https://cloud.githubusercontent.com/assets/1905485/5931824/c64e8050-a6dd-11e4-8e9d-e512aa4668a5.JPG)

**Comment by haihw** [comment]
This is ITF-14, I think it's not supported.

**Comment by yeahdongcn** [comment]
ITF-14 the length of the content should be 14 and I noticed that your code length is 18, probably this is the reason why they couldn't be recognized.
