### ISSUE TITLE
Scanner View not working while launching in Landscape orientation

### ISSUE THREAD

**Issue by kirtishjain9** [yeahdongcn/RSBarcodes#25]
Hi yeahdongcn,

Thanks a lot for providing such a wonderful Barcode Scanner.
I've implemented RSBarcodes ObjC library in my universal application.

My issue is that I'm unable to implement it for Landscape mode for iPad.

I mean when I present RSScannerViewController by keeping device in landscape mode and if I rotate my device then there is wide black color band displaying and vice - versa and cancel button is on that inactive balck color band.

Please provide support for landscape mode as well so that particularly in iPad it will be working in all kind of orientation irrespective of launching orientation of scanner view.

**Comment by yeahdongcn** [comment]
I got it. I will fix this tomorrow.

**Comment by yeahdongcn** [comment]
Fixed.
