### ISSUE TITLE
Use RSScannerViewController with iOS 9's Slide Over multitasking

### ISSUE THREAD

**Issue by matiaskorhonen** [yeahdongcn/RSBarcodes#28]
Is it possible to use RSScannerViewController in a [Slide Over](https://developer.apple.com/library/prerelease/ios/documentation/WindowsViews/Conceptual/AdoptingMultitaskingOniPad/index.html) on an iPad running iOS 9?

At appears that it's possible to use the camera while in Slide Over (or at least the Facetime app does this), but at the moment I just get a black screen when I try to scan a barcode when my app is opened in a Slide Over (screenshot below). No errors show up in the logs or console, so I don't know what's going wrong.

When running “normally”, barcode scanning works great.

![RSScannerViewController in a Slide Over](https://cloud.githubusercontent.com/assets/43314/8637646/d46e3af6-28a4-11e5-978c-24c7aba913d0.png)

**Comment by yeahdongcn** [comment]
I will have a try this weekend.

**Comment by yeahdongcn** [comment]
I received a AVCaptureSessionInterruptionReasonVideoDeviceNotAvailableWithMultipleForegroundApps notification, in the header it tells that `@constant AVCaptureSessionInterruptionReasonVideoDeviceNotAvailableWithMultipleForegroundApps
    An interruption caused when the app is running in a multi-app layout, causing resource contention
    and degraded recording quality of service. Given your present AVCaptureSession configuration, the 
    session may only be run if your app occupies the full screen.`

**Comment by matiaskorhonen** [comment]
Thanks, at least now I know that I wasn't just doing something silly…

**Comment by yeahdongcn** [comment]
Maybe you can try search some libraries with don't use `AVCaptureSession `.

**Comment by Sumit1991Saha** [comment]
@yeahdongcn do you know about any specific library which can be used to accomplish it apart from using UIImagePickerController

**Comment by yeahdongcn** [comment]
I've no idea what are you going to implement or just you want to find replacements of UIImagePickerController?
